language: r

r:
- release
- devel

os:
- linux
- osx

sudo: true
cache: packages

r_packages:
- covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
    - noam.ross@gmail.com
    on_success: change
    on_failure: change